### ISSUE TITLE
DOS learning mode

### ISSUE THREAD

**Issue by lvenier** [cwtickle/danoniplus#1563]
Details of Improvement
A Danoni dos creator

Reason for Improvement
It exists a danoni-editor but it will be hard to maintain and needs data to be imported.
I think a learning mode should be added to create dos file.

## Screenshot
![image](https://github.com/cwtickle/danoniplus/assets/17571692/01281b77-7676-4aa4-93d2-dae7d9cc2aaf)

![image](https://github.com/cwtickle/danoniplus/assets/17571692/2a4f7e80-6981-4a86-90a3-8be8f13ac40e)

## Expected Behavior
You would go a specific page : 
https://cw7.sakura.ne.jp/danoni/new
you will click on "configure music" and then you have the settings menu where you configure you song.
When you click start the dos file is created and recording the steps you do to create the dos file (could be exported to external repo).

## Other Considerations
first thinking :) to be explored

**Comment by cwtickle** [comment]
上記について、JavaScriptで実現させるにはハードルがあったので、
バージョン別の検証サイトと統合してプレビューサイトとして実装しました。
おそらくやりたいことは実現できていると思うので、クローズします。
https://danonicw.skr.jp/

Regarding the above, there were hurdles in making it happen in JavaScript, so I integrated it with the version-specific verification site and implemented it as a preview site.
Maybe that resolved this issue, so this issue is closed.
